# refer to  https://github.com/aws-samples/docker-ecr-actions-workflow
name: Docker image build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the docker image
        uses: actions/checkout@v4
      - run: docker build . --file Dockerfile --tag holidays:$(date +%s)
